# ใช้ Golang 1.23 + Alpine
FROM golang:1.23-alpine

# ตั้งค่า Working Directory
WORKDIR /app

# ติดตั้ง git และอัปเกรด Go Toolchain อัตโนมัติ
RUN apk add --no-cache git && export GOTOOLCHAIN=auto

# ติดตั้ง Air (hot reload)
RUN go install github.com/cosmtrek/air@latest

# คัดลอกไฟล์ทั้งหมดเข้า container
COPY . .

# เปิด Port API
EXPOSE 8080

# ใช้ Air รันโปรเจค
CMD ["air"]
