# ใช้ Go 1.23 (หรือเวอร์ชันล่าสุด)
FROM golang:1.23

# ตั้งค่า Working Directory
WORKDIR /app

# ติดตั้ง git และอัปเกรด Go Toolchain อัตโนมัติ
RUN apk add --no-cache git && export GOTOOLCHAIN=auto

# ติดตั้ง Air (hot reload)
RUN go install github.com/cosmtrek/air@latest

# คัดลอกไฟล์ทั้งหมดเข้า container
COPY . .

# ใช้ Air รันโปรเจค
CMD ["air"]
