FROM golang:1.24

WORKDIR /app

ENV GOTOOLCHAIN=auto

COPY go.mod go.sum ./

RUN go mod download

COPY . .
COPY .env.production .env.production

RUN go build -o server .

EXPOSE 8080

CMD ["./server"]
